# Generated by Django 5.1.6 on 2025-02-14 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoverse_app', '0002_userprivacysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandpolicies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termsandpolicies',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='termsandpolicies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
