# Generated by Django 4.2.19 on 2025-02-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoverse_app', '0002_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecuritysettings',
            name='private_account',
            field=models.BooleanField(default=False),
        ),
    ]
