# Generated by Django 4.2.19 on 2025-02-15 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echoverse_app', '0003_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesfunnel',
            name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='salesfunnel',
            name='stages',
        ),
        migrations.AlterField(
            model_name='salesfunnel',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.CreateModel(
            name='FunnelStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='echoverse_app.salesfunnel')),
            ],
        ),
    ]
