# Generated by Django 4.2.19 on 2025-02-15 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('echoverse_app', '0004_remove_salesfunnel_conversion_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediapost',
            old_name='is_published',
            new_name='posted',
        ),
        migrations.RenameField(
            model_name='socialmediapost',
            old_name='scheduled_for',
            new_name='scheduled_time',
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
