# Generated by Django 4.2.19 on 2025-02-15 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('echoverse_app', '0004_customer_last_contacted_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcampaign',
            old_name='content',
            new_name='body',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='scheduled_for',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
