# Generated by Django 5.1.6 on 2025-02-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoverse_app', '0005_salesfunnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('scheduled_for', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
