# Generated by Django 4.2.19 on 2025-02-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoverse_app', '0006_rename_posted_socialmediapost_is_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='chatbot_response',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user_message',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('User', 'User'), ('Bot', 'Bot')], default='User', max_length=10),
        ),
    ]
