# Generated by Django 5.1.6 on 2025-02-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoverse_app', '0006_socialmediapost'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intro_text', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('featured_products', models.ManyToManyField(to='echoverse_app.product')),
            ],
        ),
    ]
