from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('ai-design/<str:industry>/', views.ai_design, name='ai_design'),
    path('add-section/<int:page_id>/<str:section_name>/<str:content>/', views.add_section, name='add_section'),
    path('get-page-sections/<int:page_id>/', views.get_page_sections, name='get_page_sections'),
    path('ai-content/<str:title>/', views.ai_content, name='ai_content'),
    path('add-collaborator/<int:post_id>/<int:user_id>/<str:role>/', views.add_collaborator, name='add_collaborator'),
    path('seo-meta/<int:post_id>/', views.seo_meta, name='seo_meta'),
    path('generate-product-info/<int:product_id>/', views.generate_product_info, name='generate_product_info'),
    path('update-inventory/<int:product_id>/<int:quantity>/', views.update_inventory, name='update_inventory'),
    path('check-inventory/<int:product_id>/', views.check_inventory, name='check_inventory'),
    path('send-campaign/<int:campaign_id>/', views.send_campaign, name='send_campaign'),
    path('generate-ad/<str:product_name>/<str:target_audience>/', views.generate_ad, name='generate_ad'),
    path('create-sales-funnel/', views.create_sales_funnel, name='create_sales_funnel'),
    path('schedule-post/', views.schedule_post, name='schedule_post'),
    path('chatbot/<str:query>/', views.chatbot, name='chatbot'),
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('contact/', views.contact, name='contact'),
    path('terms-and-policies/', views.terms_and_policies, name='terms_and_policies'),
    path('footer/', views.footer, name='footer'),
    path('security-settings/', views.security_settings, name='security_settings'),
    path('privacy-preferences/', views.privacy_preferences, name='privacy_preferences'),
    path('submit-feedback/', views.submit_general_feedback, name='submit_feedback'),
    path('product/<int:product_id>/submit_review', views.submit_product_review, name='submit_product_review'),
    path('marketplace/', views.marketplace, name='marketplace'),
    path('create-product/', views.create_product, name='create_product'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('buy/<int:product_id>/', views.buy_product, name='buy_product'),
    path('list-product/', views.list_product, name='list_product'),
    path('security-settings/', views.security_settings, name='security_settings'),
    path('privacy-settings/', views.update_privacy_settings, name='privacy_settings'),
    path('two-factor-authentication/', views.enable_two_factor_authentication, name='two_factor_settings'),
]
